# vim: ts=4:sw=4:et:
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
# [".config/k9s/skins"]
#     type = "archive"
#     url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
#     stripComponents = 1
#     refreshPeriod = "168h"
#     include = ["*/dist/**"]
[".oh-my-zsh/custom/plugins/zsh-vi-mode"]
    type = "archive"
    url = "https://github.com/jeffreytse/zsh-vi-mode/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/gitui"]
    type = "archive"
    url = "https://github.com/catppuccin/gitui/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/theme/**"]
[".config/alacritty/themes"]
    type = "archive"
    url = "https://github.com/alacritty/alacritty-theme/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/tmux/plugins/catppuccin/tmux"]
    type = "archive"
    url = "https://github.com/catppuccin/tmux/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
